name: MedievalSetHome
version: 1.0
author: DanTheTechMan
main: dansplugins.sethomesystem.MedievalSetHome
api-version: "1.13"

commands:
  sethome:
  home:
  msh:

permissions:
  msg.sethome:
    default: true
  msg.home:
    default: true
  msg.help:
    default: true
  msg.forcesave:
    default: op
  msg.forceload:
    default: op