name: DansSetHome
version: '${project.version}'
author: DanTheTechMan
main: dansplugins.sethomesystem.MedievalSetHome
api-version: "1.13"

commands:
  sethome:
  home:
  dsh:

permissions:
  dsh.help:
    default: true
  dsh.home:
    default: true
  dsh.sethome:
    default: true
  dsh.home.others:
    default: op
  dsh.forcesave:
    default: op
  dsh.forceload:
    default: op