name: MedievalSetHome
version: 1.0
author: DanTheTechMan
main: dansplugins.sethomesystem.MedievalSetHome
api-version: "1.13"

commands:
  sethome:
  home:
  msh:

permissions:
  msh.sethome:
    default: true
  msh.home:
    default: true
  msh.help:
    default: true
  msh.forcesave:
    default: op
  msh.forceload:
    default: op